modLoader="javafml"
loaderVersion="[37,)"
license="All rights reserved"
issueTrackerURL="https://github.com/MeinKraft/Crimson-Chickens/issues"

[[mods]]
modId="crimsonchickens"
version="1.17.1-1.0.2"
displayName="Crimson Chickens"
displayURL="http://crimsonfluff.com/"
updateJSONURL = "https://github.com/MeinKraft/Crimson-Chickens/raw/1.17.1/update.json"
authors="ยง4Crimson_Fluff"
logoFile="logo.png"
description=''' "Clucking Hell, Im outta my league" '''
