modLoader="javafml"
loaderVersion="[${loader_version},)"
license="All rights reserved"
issueTrackerURL="https://github.com/MeinKraft/Crimson-Chickens/issues"

[[mods]]
modId="crimsonchickens"
version="${version}"
displayName="Crimson Chickens"
displayURL="http://crimsonfluff.com/"
updateJSONURL = "https://github.com/MeinKraft/Crimson-Chickens/raw/1.16.5-Official/update.json"
authors="ยง4Crimson_Fluff"
logoFile="logo.png"
description=''' "Clucking Hell, Im outta my league" '''

[[dependencies.crimsonchickens]]
    modId="minecraft"
    mandatory=true
    versionRange="[${mc_version}]"
    side="BOTH"
[[dependencies.crimsonchickens]]
    modId="forge"
    mandatory=true
    versionRange="[${forge_version},)"
    side="BOTH"
